# Generated by Django 5.2.15 on 2026-06-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('error', 'Error')], default='pending', max_length=20)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('apis_count', models.PositiveIntegerField(default=0)),
                ('docs_count', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_indexed', models.DateTimeField(blank=True, null=True)),
                ('extract_path', models.CharField(blank=True, max_length=512)),
                ('architecture_tree', models.JSONField(blank=True, default=dict)),
                ('architecture_map', models.JSONField(blank=True, default=dict)),
                ('dependency_graph', models.JSONField(blank=True, default=dict)),
                ('index_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('zip', 'ZIP Repository'), ('swagger', 'Swagger/OpenAPI'), ('docs', 'Documentation')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
