# Generated by Django 5.2.15 on 2026-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('zip', 'ZIP Repository'), ('rar', 'RAR Repository'), ('swagger', 'Swagger/OpenAPI'), ('docs', 'Documentation')], max_length=20),
        ),
    ]
